---
name: 'testing-w-container'
description: |
  This action testing-w-container.

inputs:
  repository:
    description: |
      GitHub repository to use org/repo.
    required: true
    default: ""
  token:
    description: |
      GitHub Token or OctoSts token.
    required: true
    default: ""

runs:
  using: 'docker'
  image: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:c62f679ba214ed19732bfd19a905e84fc5ee522fda5d4faf9f9c2c2788eb5c1a
  entrypoint: wolfictl
  args:
    - update
    - https://github.com/${{ inputs.repository }}
    - --release-monitoring-query=false
    - --use-gitsign
    - --github-labels=request-version-update
    - --github-labels="automated pr"
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
    GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
